version: '3.8'
services:
  mariadb:
      image: mariadb:latest
      volumes:
        - data:/var/lib/mysql
      restart: always
      env_file:
          - ./packages/backend/.env

  backend:
      ##restart: always
      container_name: backend
      image: node:14.15.0
      working_dir: /usr/app/packages/backend/src
      volumes:
        - ./packages/backend/src:/usr/app/packages/backend/src
      environment: 
          - PORT=3000
      depends_on:
          - mariadb
      ports:
          - "3000:3000"
      env_file:
          - ./packages/backend/.env
      command: /bin/bash -c "npm install && npm run start"

  frontend:
    image: node:14.15.0
    container_name: frontend
    working_dir: /usr/app/packages/frontend
    ports:
      - 2000:2000
    command: /bin/bash -c "npm install && npm run start"
    stdin_open: true
    volumes:
      - ./packages/frontend:/usr/app/packages/frontend

volumes:
  data:
