version: "3"
services:
  taskMasterAPI:
    image: $IMAGE_TAG_SERVER
    build: ./api
    environment:
      - API_PORT=8080
      - API_HOST=http://taskMasterAPI
      - DBHOST=mariadb
      - MYSQL_USER=exampleuser
      - MYSQL_PASSWORD=examplepwd
      - MYSQL_DATABASE=exampledb
      - NODE_ENV=local
    depends_on:
      - db

  db:
    image: mariadb:latest
    env_file:
          - ./packages/backend/.env
  nginx:
    image: $IMAGE_TAG_NGINX
    depends_on:
      - taskMasterAPI

  cypress:
    image: $IMAGE_TAG_CYPRESS
    environment:
      - CYPRESS_baseUrl=http://nginx:8080
